server:
  port: 8080

spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DBURL}:3306/ai_co?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      io.netty.resolver.dns: DEBUG

#jwt:
#  secret-key-source: ${SECRETKEY}  # JWT ???
