server:
  port: 8080

spring:
  datasource:
    username: ENC(kDzFXBJiFKoHgqGkXBfkcJcx+h/jfbfI)
    password: ENC(nzzlEhN4gb48ggOclgLrInFeIhSbRQP+)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://aico-database.cf8sa4okg694.ap-northeast-2.rds.amazonaws.com:3306/ai_co?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate.jdbc.batch_size: 50  # 한 번에 저장할 최대 엔티티 수
      hibernate.order_inserts: true  # 삽입 순서 최적화
      hibernate.order_updates: true  # 업데이트 순서 최적화
      hibernate.flush.mode: COMMIT  # Batch 후 flush 시점 설정


  logging:
    level:
      io.netty.resolver.dns: DEBUG

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ENC(n15HgIvBgd1Wcdu4NbyeAmi40GkKZcxrZoH7HX2nyrI=)
    password: ENC(DcdivENQDEeS7tVQ3NBzgdPiL7DA9LQTNNLcL7p08DM=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  data:
    redis:
      #host: localhost
      host: ENC(n60mvykJRU2R5SBqLmUiyatj973/jexg) #ENC(4i+ka2OLOJPRQUSzIXfseA6RSvcUhwx7) # 추후 ec2 프라이빗 아이피로 변경 필요2.
      port: 6379
      password: ENC(4jc8zprzCJTQ3qjGiSwInQ==)


jwt:
  secret-key-source: ENC(TH3JEhaFp/YER6btYCYQ99ZH9nDc/zuXPIVNM/JnshmEAOsccENF1WNlkkII/0xt)
jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

cloud:
  aws:
    credentials:
      access-key: ENC(StjTgKvyFk/Nidrg+8RTa45y9Vi21Eb8F14uz8o+zxY=)
      secret-key: ENC(8xy66S8/lLySwyyvgkqmUeQIKdy5MHfgU00VE2Mt9Jz8YTsmKCd6fJZMRihXqWfi+g5C5o+sPs0=)
    region:
      static: ap-northeast-2  # 서울 리전
    s3:
      bucket: aicoproject
